### ISSUE TITLE
how did you manage to misspell terminal 

### ISSUE THREAD

**Issue by environment-dev** [8ua/8ua#1]
[lmfao](https://github.com/8ua/8ua/blob/f64a9444559afa54a8ed866b7bef95fff38cd598/README.md?plain=1#L14)

![Screen Shot 2021-12-19 at 2 49 17 PM](https://user-images.githubusercontent.com/81181499/146693708-0d7e7cd3-8116-4b8e-960e-8c0872865e8d.png)

![Screen Shot 2021-12-19 at 2 50 15 PM](https://user-images.githubusercontent.com/81181499/146693736-8d7a0c39-13ed-4bf2-8b4e-50bd87f96557.png)
^ learn how to spell it correctly
ty

**Comment by environment-dev** [comment]
to be fair this entire profile repo is prob among the worst ive ever seen

this is satire, right?

**Comment by environment-dev** [comment]
issue fixed by commit 6202f778bf88352548dbcb55e4c53fc8f2bff949, but still, 


this is satire right lmfao

**Comment by 8ua** [comment]
> 

bros been here for 20 minutes looking at my profile

**Comment by environment-dev** [comment]
find me something better to do

**Comment by 8ua** [comment]
> find me something better to do

Rewrite all my code in Jew-Lang

**Comment by environment-dev** [comment]
![Screen Shot 2021-12-19 at 3 12 28 PM](https://user-images.githubusercontent.com/81181499/146694375-288c0943-54bd-4c1f-8d06-c14f8f61e8f8.png)
LMFAO FASTED

**Comment by environment-dev** [comment]
> > find me something better to do
> 
> Rewrite all my code in Jew-Lang

thats ur lang though

**Comment by 8ua** [comment]
> ![Screen Shot 2021-12-19 at 3 12 28 PM](https://user-images.githubusercontent.com/81181499/146694375-288c0943-54bd-4c1f-8d06-c14f8f61e8f8.png) LMFAO FASTED

Fasted is a word.

**Comment by 8ua** [comment]
> > > find me something better to do
> > 
> > 
> > Rewrite all my code in Jew-Lang
> 
> thats ur lang though

How do you know that?

**Comment by environment-dev** [comment]
![Screen Shot 2021-12-19 at 3 14 06 PM](https://user-images.githubusercontent.com/81181499/146694429-8d757fd7-04ad-4b9a-9235-55cbebc65cdd.png)


> > ![Screen Shot 2021-12-19 at 3 12 28 PM](https://user-images.githubusercontent.com/81181499/146694375-288c0943-54bd-4c1f-8d06-c14f8f61e8f8.png) LMFAO FASTED
> 
> Fasted is a word.

fasted is past tense, implying it was the fastest at one point but now isnt lmfao

**Comment by environment-dev** [comment]
> > > > find me something better to do
> > > 
> > > 
> > > Rewrite all my code in Jew-Lang
> > 
> > 
> > thats ur lang though
> 
> How do you know that?

you make it quite clear fam

**Comment by 8ua** [comment]
> ![Screen Shot 2021-12-19 at 3 14 06 PM](https://user-images.githubusercontent.com/81181499/146694429-8d757fd7-04ad-4b9a-9235-55cbebc65cdd.png)
> 
> > > ![Screen Shot 2021-12-19 at 3 12 28 PM](https://user-images.githubusercontent.com/81181499/146694375-288c0943-54bd-4c1f-8d06-c14f8f61e8f8.png) LMFAO FASTED
> > 
> > 
> > Fasted is a word.
> 
> fasted is past tense, implying it was the fastest at one point but now isnt lmfao

What would i use instead then bud, look at my cute pfp now its a cute snake, ahahhaha

**Comment by environment-dev** [comment]
![Screen Shot 2021-12-19 at 3 16 40 PM](https://user-images.githubusercontent.com/81181499/146694508-88239922-ffb9-4bcd-ae5b-3af912c80e5f.png)
you baby your users for some weird reason 😭

**Comment by environment-dev** [comment]
> look at my cute pfp now its a cute snake, ahahhaha

how does this relate to anything currently being discussed?

**Comment by 8ua** [comment]
> ![Screen Shot 2021-12-19 at 3 16 40 PM](https://user-images.githubusercontent.com/81181499/146694508-88239922-ffb9-4bcd-ae5b-3af912c80e5f.png) you baby your users for some weird reason 😭

because some people dont know the basics, if you look at other python repos, it will explain and why is that a issue for you?

**Comment by 8ua** [comment]
> > look at my cute pfp now its a cute snake, ahahhaha
> 
> how does this relate to anything currently being discussed?

because im trolling, u take this platform serious, im never active on github!!!

**Comment by environment-dev** [comment]
> > ![Screen Shot 2021-12-19 at 3 16 40 PM](https://user-images.githubusercontent.com/81181499/146694508-88239922-ffb9-4bcd-ae5b-3af912c80e5f.png) you baby your users for some weird reason 😭
> 
> because some people dont know the basics, if you look at other python repos, it will explain and why is that a issue for you?

your target userbase shouldn't need basic stuff like this explained to them ?

**Comment by environment-dev** [comment]
> > > look at my cute pfp now its a cute snake, ahahhaha
> > 
> > 
> > how does this relate to anything currently being discussed?
> 
> because im trolling, u take this platform serious, im never active on github!!!

yea ik i legit told u to find me something better to do

**Comment by 8ua** [comment]
> > > > look at my cute pfp now its a cute snake, ahahhaha
> > > 
> > > 
> > > how does this relate to anything currently being discussed?
> > 
> > 
> > because im trolling, u take this platform serious, im never active on github!!!
> 
> yea ik i legit told u to find me something better to do

What do you like?

**Comment by environment-dev** [comment]
i have way too much time on my hands, might as-well waste some of it eh?

**Comment by environment-dev** [comment]
> > > > > look at my cute pfp now its a cute snake, ahahhaha
> > > > 
> > > > 
> > > > how does this relate to anything currently being discussed?
> > > 
> > > 
> > > because im trolling, u take this platform serious, im never active on github!!!
> > 
> > 
> > yea ik i legit told u to find me something better to do
> 
> What do you like?

i thought we are bffs...

**Comment by 8ua** [comment]
> > > ![Screen Shot 2021-12-19 at 3 16 40 PM](https://user-images.githubusercontent.com/81181499/146694508-88239922-ffb9-4bcd-ae5b-3af912c80e5f.png) you baby your users for some weird reason 😭
> > 
> > 
> > because some people dont know the basics, if you look at other python repos, it will explain and why is that a issue for you?
> 
> your target userbase shouldn't need basic stuff like this explained to them ?

This was made almost 1 year ago, like I said people are stupid and don't know the basics of installing Python. It also doesn't make people create issues, about simple errors because Python isn't added to path, etc.

**Comment by 8ua** [comment]
> > > > > > look at my cute pfp now its a cute snake, ahahhaha
> > > > > 
> > > > > 
> > > > > how does this relate to anything currently being discussed?
> > > > 
> > > > 
> > > > because im trolling, u take this platform serious, im never active on github!!!
> > > 
> > > 
> > > yea ik i legit told u to find me something better to do
> > 
> > 
> > What do you like?
> 
> i thought we are bffs...

I guess so?

**Comment by environment-dev** [comment]
> This was made almost 1 year ago, like I said people are stupid and don't know the basics of installing Python. It also doesn't make people create issues, about simple errors because Python isn't added to path, etc.

https://github.com/8ua/Discord-Creator/issues/5 
https://github.com/8ua/Discord-Creator/issues/4
ig ur right doe, it just seems weird to me xd + the linked u provided for the python download is for windows, just send them to the main py webpage next time

**Comment by 8ua** [comment]
> 

This project is not maintained anymore, since its patched

**Comment by environment-dev** [comment]
why did u publicly put out nord accs by the way xd

**Comment by 8ua** [comment]
> 

so people don't add me on Disord for an account, just easier for me. I mean im pretty sure all those accounts are locked now anyways.

**Comment by environment-dev** [comment]
suggestion: use res proxies next time, maybe the accounts wont get locked ¯\_(ツ)_/¯

**Comment by 8ua** [comment]
> I have a gen that uses residential proxies, but discord has banned most proxies or they're flagged. The best proxies to evade locking on creation is actually mobile proxies, 4g proxies to be specific

**Comment by environment-dev** [comment]
> > I have a gen that uses residential proxies, but discord has banned most proxies or they're flagged. The best proxies to evade locking on creation is actually mobile proxies, 4g proxies to be specific

discord has been hammering down on alts recently, which is kinda surprising considering they added a multi account switcher experiment not long ago

**Comment by 8ua** [comment]
> 

yep i know. There is actually a cool way to bypass phone locks though. You can use Playwright which is basically selenium but has a lot more options. With Playwright you can spoof your geolocation and choose your specfic device. If you set the Playwright device to Nokia, it will actually bypass hcaptcha too.

**Comment by environment-dev** [comment]
> > 
> 
> yep i know. There is actually a cool way to bypass phone locks though. You can use Playwright which is basically selenium but has a lot more options. With Playwright you can spoof your geolocation and choose your specfic device. If you set the Playwright device to Nokia, it will actually bypass hcaptcha too.

thats actually hilarious

**Comment by 8ua** [comment]
> > > 
> > 
> > 
> > yep i know. There is actually a cool way to bypass phone locks though. You can use Playwright which is basically selenium but has a lot more options. With Playwright you can spoof your geolocation and choose your specfic device. If you set the Playwright device to Nokia, it will actually bypass hcaptcha too.
> 
> thats actually hilarious

yep
